server:
  port: 5000
  error:
    include-stacktrace: never

spring:
  mvc:
    async:
      request-timeout: 1000

app:
  endpointsMap:
    similar-ids: http://localhost:3001/product/{productId}/similarids
    product-url: http://localhost:3001/product/{productId}

